name: pro_lints
description: Common Lints package.

repository: https://github.com/pro100andrey/pro_lints
issue_tracker: https://github.com/pro100andrey/pro_lints/issues
homepage: https://github.com/pro100andrey/pro_lints
documentation: https://github.com/pro100andrey/pro_lints/blob/main/README.md

version: 1.0.0

environment:
  sdk: ^3.0.0

dev_dependencies:
  dart_code_metrics: ^5.7.5