name: lint
description: Common Lints package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  dart_code_metrics: ^4.20.0