name: lint
description: Common Lints package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  analyzer: ^5.0.0
  dart_code_metrics: ^4.19.0

dependency_overrides:
  analyzer: ^5.0.0
  analyzer_plugin: 0.11.1