name: lint
description: Common Lints package.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_code_metrics: ^5.7.3